### ISSUE TITLE
Design Decision

### ISSUE THREAD

**Issue by dak-x** [dak-x/weatherapp#2]
Since the api requires a token, currently the `build.sh` file appends code to the `lib.rs`which may break the ode if the build fails. Design a better procedure to incorporate for the api-key needed and replace the existing with the same.

**Comment by DominicD** [comment]
This could be done in a build.rs script. Which has the benefit that it will be run with normal cargo build command.
Another possibility would be to read it in runtime.

**Comment by dak-x** [comment]
Hi. I was using a build.rs script, I do not want to process the entire source code to search for the token, and if not present insert it. I need something like a build time solution, which happens to be proc-macros. I have figured this out. I could also use an env-variable and set it permanently. Btw Thank You for showing interest.

**Comment by DominicD** [comment]
I am interested to see how you will solve this. Will you commit it soon?

**Comment by dak-x** [comment]
@DominicD Ideally, as you mentioned, I should use a build.rs script. But on VsCode on every subsequent save, It was running the build.rs and then re-appending the App_Token, causing re-declaration error. So a solution is to use Proc-Macros as they run at compile time. So I could use an empty macro symbol to replace it with the token after reading it from the token.txt file, Since this happens before compilation it should work. If you need a good exercise on rust macros check this out. https://github.com/dtolnay/proc-macro-workshop It has some great exercises if you wish to learn rust macros in detail. But It does need prior knowledge of ASTs and geeking through the documentation. Yes, I will commit hopefully by Sunday.

**Comment by DominicD** [comment]
If you put this in build.rs:

```
// Tell cargo to invalidate the built crate whenever the wrapper changes
println!("cargo:rerun-if-changed=token.txt");
```

It will run only on first time and if token.txt changed. 

It's a little bit hacky bit this works (assuming there is an empty last line in lib.rs otherwise it can delete the last line of code): 
```
use std::path::{Path, PathBuf};
use std::io::{Write, BufRead};
use std::fs::*;
use std::io;

fn main() {
    // Tell Cargo that if the given file changes, to rerun this build script.
    println!("cargo:rerun-if-changed=token.txt");

    let api_token = read_to_string("token.txt").expect("Could not read token.txt");
    let api_token_const_string = format!("const APP_ID:&str = \"{}\";", api_token);

    let file = File::open("src\\lib.rs").unwrap();
    let lines = io::BufReader::new(file).lines().collect::<Vec<Result<String, io::Error>>>();

    let lines_count = lines.len();
    let mut s = lines
        .into_iter()
        .take(lines_count-1)
        .map(|line| line.unwrap_or("".to_string()) + "\n")
        .collect::<String>();

    s += api_token_const_string.as_str();
    write("src\\lib.rs", s);

} 
```

Thanks for the info about the macro, haven't looked into that yet.

**Comment by dak-x** [comment]
@DominicD Hey! I found another solution. Check this macro https://doc.rust-lang.org/std/macro.option_env.html and also https://doc.rust-lang.org/std/macro.env.html. It looks the value at compile time and replaces that it in the code. So you may set the env_var in the build.rs file and then let the macro do its work in lib.rs

**Comment by DominicD** [comment]
Oh yeah that seems to be the perfect solution!
